//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flexion.Assets.Localization.EditorLocalization.LayerEditorLocalization.Helper {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LayerEditorHelperLocalization_fr {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LayerEditorHelperLocalization_fr() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Flexion.Assets.Localization.EditorLocalization.LayerEditorLocalization.Helper.Lay" +
                            "erEditorHelperLocalization_fr", typeof(LayerEditorHelperLocalization_fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string LayerEditorHelper1 {
            get {
                return ResourceManager.GetString("LayerEditorHelper1", resourceCulture);
            }
        }
        
        internal static string LayerEditorHelper2 {
            get {
                return ResourceManager.GetString("LayerEditorHelper2", resourceCulture);
            }
        }
        
        internal static string LayerEditorHelper3 {
            get {
                return ResourceManager.GetString("LayerEditorHelper3", resourceCulture);
            }
        }
        
        internal static string LayerEditorHelper4 {
            get {
                return ResourceManager.GetString("LayerEditorHelper4", resourceCulture);
            }
        }
        
        internal static string LayerEditorHelper5 {
            get {
                return ResourceManager.GetString("LayerEditorHelper5", resourceCulture);
            }
        }
        
        internal static string LayerEditorHelper6 {
            get {
                return ResourceManager.GetString("LayerEditorHelper6", resourceCulture);
            }
        }
        
        internal static string LayerEditorHelper7 {
            get {
                return ResourceManager.GetString("LayerEditorHelper7", resourceCulture);
            }
        }
        
        internal static string LayerEditorHelper8 {
            get {
                return ResourceManager.GetString("LayerEditorHelper8", resourceCulture);
            }
        }
    }
}
