//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flexion.Assets.Localization.EditorLocalization.MaterialEditorLocalization.Helper {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MaterialEditorHelperLocalization_fr {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MaterialEditorHelperLocalization_fr() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Flexion.Assets.Localization.EditorLocalization.MaterialEditorLocalization.Helper." +
                            "MaterialEditorHelperLocalization_fr", typeof(MaterialEditorHelperLocalization_fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string MaterialEditorHelper1 {
            get {
                return ResourceManager.GetString("MaterialEditorHelper1", resourceCulture);
            }
        }
        
        internal static string MaterialEditorHelper2 {
            get {
                return ResourceManager.GetString("MaterialEditorHelper2", resourceCulture);
            }
        }
        
        internal static string MaterialEditorHelper3 {
            get {
                return ResourceManager.GetString("MaterialEditorHelper3", resourceCulture);
            }
        }
    }
}
