//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexionV2.Assets.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_fr {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_fr() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FlexionV2.Assets.Localization.Resources_fr", typeof(Resources_fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Begin {
            get {
                return ResourceManager.GetString("Begin", resourceCulture);
            }
        }
        
        internal static string ForceWithColon {
            get {
                return ResourceManager.GetString("ForceWithColon", resourceCulture);
            }
        }
        
        internal static string LayersWithColon {
            get {
                return ResourceManager.GetString("LayersWithColon", resourceCulture);
            }
        }
        
        internal static string MaterialsWithColon {
            get {
                return ResourceManager.GetString("MaterialsWithColon", resourceCulture);
            }
        }
        
        internal static string PiecesWithColon {
            get {
                return ResourceManager.GetString("PiecesWithColon", resourceCulture);
            }
        }
        
        internal static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        internal static string Center {
            get {
                return ResourceManager.GetString("Center", resourceCulture);
            }
        }
        
        internal static string Sides {
            get {
                return ResourceManager.GetString("Sides", resourceCulture);
            }
        }
        
        internal static string Layers {
            get {
                return ResourceManager.GetString("Layers", resourceCulture);
            }
        }
        
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        internal static string NameWithColon {
            get {
                return ResourceManager.GetString("NameWithColon", resourceCulture);
            }
        }
        
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        internal static string MaterialWithColon {
            get {
                return ResourceManager.GetString("MaterialWithColon", resourceCulture);
            }
        }
        
        internal static string WidthCenterWithColon {
            get {
                return ResourceManager.GetString("WidthCenterWithColon", resourceCulture);
            }
        }
        
        internal static string WidthSidesWithColon {
            get {
                return ResourceManager.GetString("WidthSidesWithColon", resourceCulture);
            }
        }
        
        internal static string HeightCenterWithColon {
            get {
                return ResourceManager.GetString("HeightCenterWithColon", resourceCulture);
            }
        }
        
        internal static string HeightOnSidesWithColon {
            get {
                return ResourceManager.GetString("HeightOnSidesWithColon", resourceCulture);
            }
        }
        
        internal static string MassWithColon {
            get {
                return ResourceManager.GetString("MassWithColon", resourceCulture);
            }
        }
        
        internal static string GravityWithColon {
            get {
                return ResourceManager.GetString("GravityWithColon", resourceCulture);
            }
        }
        
        internal static string RadiusWithColon {
            get {
                return ResourceManager.GetString("RadiusWithColon", resourceCulture);
            }
        }
        
        internal static string SpeedWithColon {
            get {
                return ResourceManager.GetString("SpeedWithColon", resourceCulture);
            }
        }
        
        internal static string LengthWithColon {
            get {
                return ResourceManager.GetString("LengthWithColon", resourceCulture);
            }
        }
        
        internal static string ChangeLayers {
            get {
                return ResourceManager.GetString("ChangeLayers", resourceCulture);
            }
        }
        
        internal static string InPieceWithColon {
            get {
                return ResourceManager.GetString("InPieceWithColon", resourceCulture);
            }
        }
        
        internal static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        internal static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        internal static string AvailableWithColon {
            get {
                return ResourceManager.GetString("AvailableWithColon", resourceCulture);
            }
        }
        
        internal static string LanguageWithColon {
            get {
                return ResourceManager.GetString("LanguageWithColon", resourceCulture);
            }
        }
    }
}
