//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flexion.Assets.Localization.EditorLocalization.PieceEditorLocalization.Helper {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PieceEditorHelperLocalization_fr {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PieceEditorHelperLocalization_fr() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Flexion.Assets.Localization.EditorLocalization.PieceEditorLocalization.Helper.Pie" +
                            "ceEditorHelperLocalization_fr", typeof(PieceEditorHelperLocalization_fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string PieceEditorHelper6 {
            get {
                return ResourceManager.GetString("PieceEditorHelper6", resourceCulture);
            }
        }
        
        internal static string PieceEditorHelper5 {
            get {
                return ResourceManager.GetString("PieceEditorHelper5", resourceCulture);
            }
        }
        
        internal static string PieceEditorHelper1 {
            get {
                return ResourceManager.GetString("PieceEditorHelper1", resourceCulture);
            }
        }
        
        internal static string PieceEditorHelper2 {
            get {
                return ResourceManager.GetString("PieceEditorHelper2", resourceCulture);
            }
        }
        
        internal static string PieceEditorHelper3 {
            get {
                return ResourceManager.GetString("PieceEditorHelper3", resourceCulture);
            }
        }
        
        internal static string PieceEditorHelper4 {
            get {
                return ResourceManager.GetString("PieceEditorHelper4", resourceCulture);
            }
        }
    }
}
