//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BendingCalculator.Assets.Localization.EditorLocalization.PieceEditorLocalization {
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PieceEditorLocalization_fr {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PieceEditorLocalization_fr() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("BendingCalculator.Assets.Localization.EditorLocalization.PieceEditorLocalization.PieceEdito" +
                            "rLocalization_fr", typeof(PieceEditorLocalization_fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AvailableWithColon {
            get {
                return ResourceManager.GetString("AvailableWithColon", resourceCulture);
            }
        }
        
        internal static string ChangeLayers {
            get {
                return ResourceManager.GetString("ChangeLayers", resourceCulture);
            }
        }
        
        internal static string InPieceWithColon {
            get {
                return ResourceManager.GetString("InPieceWithColon", resourceCulture);
            }
        }
        
        internal static string LayersWithColon {
            get {
                return ResourceManager.GetString("LayersWithColon", resourceCulture);
            }
        }
        
        internal static string LengthWithColon {
            get {
                return ResourceManager.GetString("LengthWithColon", resourceCulture);
            }
        }
        
        internal static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        internal static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
    }
}
