//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BendingCalculator.Assets.Localization.EditorLocalization.LayerEditorLocalization {
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LayerEditorLocalization {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LayerEditorLocalization() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("BendingCalculator.Assets.Localization.EditorLocalization.LayerEditorLocalization.LayerEdito" +
                            "rLocalization", typeof(LayerEditorLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string HeightCenterWithColon {
            get {
                return ResourceManager.GetString("HeightCenterWithColon", resourceCulture);
            }
        }
        
        internal static string HeightOnSidesWithColon {
            get {
                return ResourceManager.GetString("HeightOnSidesWithColon", resourceCulture);
            }
        }
        
        internal static string WidthCenterWithColon {
            get {
                return ResourceManager.GetString("WidthCenterWithColon", resourceCulture);
            }
        }
        
        internal static string WidthSidesWithColon {
            get {
                return ResourceManager.GetString("WidthSidesWithColon", resourceCulture);
            }
        }
        
        internal static string MaterialWithColon {
            get {
                return ResourceManager.GetString("MaterialWithColon", resourceCulture);
            }
        }
    }
}
