//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flexion.Assets.Localization.EditorLocalization.ForceEditorLocalization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ForceEditorLocalization {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ForceEditorLocalization() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Flexion.Assets.Localization.EditorLocalization.ForceEditorLocalization.ForceEdito" +
                            "rLocalization", typeof(ForceEditorLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ForceWithColon {
            get {
                return ResourceManager.GetString("ForceWithColon", resourceCulture);
            }
        }
        
        internal static string MassWithColon {
            get {
                return ResourceManager.GetString("MassWithColon", resourceCulture);
            }
        }
        
        internal static string RadiusWithColon {
            get {
                return ResourceManager.GetString("RadiusWithColon", resourceCulture);
            }
        }
        
        internal static string GravityWithColon {
            get {
                return ResourceManager.GetString("GravityWithColon", resourceCulture);
            }
        }
        
        internal static string SpeedWithColon {
            get {
                return ResourceManager.GetString("SpeedWithColon", resourceCulture);
            }
        }
    }
}
