//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BendingCalculator.Assets.Localization.Static {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Static {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Static() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("BendingCalculator.Assets.Localization.Static.Static", typeof(Static).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string SideViewWithColon {
            get {
                return ResourceManager.GetString("SideViewWithColon", resourceCulture); 
            }
        }
        
        public static string TopViewWithColon {
            get {
                return ResourceManager.GetString("TopViewWithColon", resourceCulture); 
            }
        }
        
        public static string Center {
            get {
                return ResourceManager.GetString("Center", resourceCulture); 
            }
        }
        
        public static string Sides {
            get {
                return ResourceManager.GetString("Sides", resourceCulture); 
            }
        }
        
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture); 
            }
        }
        
        public static string Layers {
            get {
                return ResourceManager.GetString("Layers", resourceCulture); 
            }
        }
        
        public static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture); 
            }
        }
        public static string XAxisName {
            get {
                return ResourceManager.GetString("XAxisName", resourceCulture); 
            }
        }
        
        public static string YAxisName {
            get {
                return ResourceManager.GetString("YAxisName", resourceCulture); 
            }
        }
    }
}
